In [2]:
import tensorflow as tf

w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)

print(y)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [3]:
a = tf.zeros([3, 4], dtype = 'int32')
print(a)
b = tf.constant([1, 2, 3, 4, 5, 6, 7])
print(b)
c = tf.random.normal([2,3], mean=-1, stddev=4)
print(c)
d = tf.random.shuffle(c)
print(d)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor(
[[ -7.561867   -3.5363588   2.383294 ]
 [ -0.4473791  -7.707698  -10.605548 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ -0.4473791  -7.707698  -10.605548 ]
 [ -7.561867   -3.5363588   2.383294 ]], shape=(2, 3), dtype=float32)


In [4]:
import numpy as np
a = np.ones((3,3))
ta = tf.convert_to_tensor(a)
print(ta)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)


In [11]:
#input1 = tf.placeholder(tf.float32)  #legacy
input1 = tf.Variable([[1.0, 2.0],[3.0, 4.0]], [2, 2], dtype=tf.float32)
input2 = tf.Variable([[2.0, 2.0],[1.0, 2.0]], [2, 2], dtype=tf.float32)
output = tf.multiply(input1, input2) 
print(output)
input1 = tf.Variable(tf.ones([2,2]), [2, 2], dtype=tf.float32)
input2 = tf.Variable([[2.0, 2.0],[1.0, 2.0]], [2, 2], dtype=tf.float32)
output = tf.matmul(input1, input2)
print(output)

tf.Tensor(
[[2. 4.]
 [3. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 4.]
 [3. 4.]], shape=(2, 2), dtype=float32)
